@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!theme plain
skinparam componentStyle uml2
skinparam shadowing false
skinparam roundcorner 15
skinparam monochrome true
skinparam backgroundColor #F9F9F9
skinparam ArrowColor Black
skinparam ArrowFontColor Black
skinparam defaultFontName "Nanum Gothic"

skinparam linetype ortho

Person(user, "User", "Web App User")
System_Ext(github, "GitHub", "Source Code Repository")

System_Boundary(aws, "AWS Cloud") {

    System_Boundary(vpc, "VPC") {
        Container(alb, "Application Load Balancer", "Technology: AWS ALB", "Distributes incoming traffic")

        System_Boundary(private_subnet, "Private Subnet (Multi-AZ)") {
            Container(ecs_service, "ECS Service", "Technology: Docker", "Runs the containerized application")
            ContainerDb(rds, "RDS Database", "Technology: PostgreSQL", "Stores application data")
        }
    }

    System_Boundary(cicd, "CI/CD Pipeline") {
        Container(pipeline, "CodePipeline", "Technology: AWS Service", "Orchestrates the deployment process")
        Container(codebuild, "CodeBuild", "Technology: AWS Service", "Builds Docker image")
        Container(ecr, "ECR", "Technology: AWS Service", "Stores Docker images")
        Container(s3, "S3 Bucket", "Technology: AWS Service", "Stores build artifacts")
    }

}

Rel(user, alb, "Sends HTTPS request")
Rel(alb, ecs_service, "Forwards traffic")
Rel(ecs_service, rds, "Reads/Writes data", "SQL")

Rel(github, pipeline, "Triggers via Webhook")
Rel(pipeline, codebuild, "Triggers build")
Rel(codebuild, ecr, "Pushes image")
Rel(codebuild, s3, "Stores artifacts")
Rel(pipeline, ecs_service, "Deploys new version")


@enduml
