version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo "$EC2_SSH_KEY" > /tmp/saiondo.pem
      - chmod 600 /tmp/saiondo.pem
      - chmod +x deploy.sh
  build:
    commands:
      - echo "Deploying backend/api, backend/llm, postgres to EC2"
      - scp -i /tmp/saiondo.pem -o StrictHostKeyChecking=no -r ./api ./llm ./docker-compose.yml deploy.sh $EC2_USER@$EC2_HOST:/home/ec2-user/saiondo-backend/
      - ssh -i /tmp/saiondo.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
          cd /home/ec2-user/saiondo-backend &&
          bash deploy.sh
        '
artifacts:
  files:
    - '**/*'
