name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # A
  another_flushbar: ^1.12.30
  awesome_dialog: ^3.2.1
  # C
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  cloud_functions: ^4.6.5
  cloud_firestore: ^4.15.5
  # D
  dio: ^5.7.0
  # E
  event_bus: ^2.0.0
  # F
  flutter_mobx: ^2.2.0
  flutter_slider_drawer: ^2.1.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.8.5
  flutter_dotenv: ^5.2.1
  # G
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  # H
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # I
  intl: ^0.19.0
  # L
  loading_animation_widget: ^1.2.1
  logger: ^2.4.0
  # M
  mobx: ^2.3.0
  # P
  path_provider: ^2.1.1
  # S
  shared_preferences: ^2.2.2
  sembast: ^3.6.0
  sembast_web: ^2.3.0
  # V
  validators: ^3.0.0
  # X
  xxtea: ^2.1.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^5.10.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700