@startuml
skinparam linetype ortho
skinparam rectangle {
  RoundCorner 10
}

entity User {
  * id : String
  * email : String
  * password : String
  * gender : Gender
  * birthDate : DateTime
}

entity UserProfile {
  * id : String
  * userId : String
  * name : String
  * fcmToken : String
  * point : Int
}

entity UserSubscription {
  * id : String
  * userId : String
  * isSubscribed : Boolean
  * subscriptionUntil : DateTime
}

entity Wallet {
  * id : String
  * userId : String
  * address : String
  * privateKey : String
  * tokenBalance : String
}

entity Channel {
  * id : String
  * inviteCode : String
  * status : String
  * startedAt : DateTime
}

entity ChannelMember {
  * id : String
  * userId : String
  * channelId : String
  * role : String
  * joinedAt : DateTime
}

entity Chat {
  * id : String
  * channelId : String
  * senderType : String << 'user' or 'assistant' >>
  * senderId : String
  * message : String
  * createdAt : DateTime
}

entity Assistant {
  * id : String
  * name : String
}

entity CoupleAnalysis {
  * id : String
  * channelId : String
  * rawResult : String
}

entity PersonaProfile {
  * id : String
  * userId : String
  * categoryCodeId : String
  * content : String
  * confidenceScore : Float
  * isStatic : Boolean
}

entity CategoryCode {
  * id : String
  * code : String
  * description : String
}

entity PushSchedule {
  * id : String
  * userId : String
  * scheduledAt : DateTime
  * sentAt : DateTime
  * status : PushStatus
}

entity UserAnswer {
  * id : String
  * pushScheduleId : String
  * answerText : String
  * createdAt : DateTime
}

entity Advice {
  * id : String
  * channelId : String
  * advice : String
  * generatedById : String
}

' 관계 설정
User ||--o{ UserProfile
User ||--o{ Wallet
User ||--o{ ChannelMember
User ||--o{ PushSchedule
User ||--o{ UserSubscription
User ||--o{ PersonaProfile

Channel ||--o{ ChannelMember
Channel ||--o{ Chat
Channel ||--o{ CoupleAnalysis
Channel ||--o{ Advice

Assistant ||--o{ Chat

PushSchedule ||--o{ UserAnswer
PersonaProfile }o--|| CategoryCode

@enduml
